# Generated by Django 3.1.5 on 2021-01-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('album', models.CharField(max_length=120)),
                ('external_url', models.CharField(max_length=200, unique=True)),
                ('preview_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_recs', models.ManyToManyField(to='music.SongRec')),
            ],
        ),
    ]
