# Generated by Django 3.1.5 on 2021-01-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrec',
            old_name='spotiftID',
            new_name='spotifyID',
        ),
    ]
