# Generated by Django 3.1.5 on 2021-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrec',
            name='preview_url',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
