# Generated by Django 3.1.5 on 2021-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210130_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrec',
            old_name='spotifyID',
            new_name='album',
        ),
        migrations.AddField(
            model_name='songrec',
            name='external_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrec',
            name='preview_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
