# Generated by Django 3.1.5 on 2021-01-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210131_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrec',
            name='preview_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
