# Generated by Django 3.1.5 on 2021-01-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210131_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(default='N/A', max_length=120, serialize=False),
        ),
    ]
