# Generated by Django 3.1.5 on 2021-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210131_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
